import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer"
export const metadata: Metadata = {
  title: "Booking Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <Header/>
      <body className="min-h-full flex flex-col">{children}</body>
      <Footer/>
    </html>
  );
}
